import React from "react";
export const metadata = {
  title: 'Mindmap Flow - Bảng giá',
  description: 'Generated by create next app',
}
const Price = () => {
  return (
    <div className="min-h-screen pb-28 mb-80 sm:pb-0">
      <div className="lg:h-[767px] ">
        <div className="max-w-7xl min-h-screen mx-auto p-4 sm:p-10 lg:py-20">
          <div className="max-w-5xl mx-auto text-center text-white tracking-widest pb-10 lg:pb-20">
            <p className="pb-4 text-xl text-gray-500">PRICING</p>
            <h1 className="text-3xl sm:text-5xl font-black text-gray-500 ">
              The right price for you, whoeveryou are
            </h1>
            <p className="text-xl sm:text-2xl font-light text-gray-500 px-10 py-6">
              Lorem ipsum has been the industrys standard dummy text ever since
              , when an unknown printer took a galley of type and scrambled.
            </p>
          </div>
          <div className="flex flex-col lg:flex-row justify-center items-center  gap-8 lg:gap-0 lg:mt-4">
            <div className="flex-1 w-full mb-6 bg-white rounded-xl shadow-xl lg:scale-95">
              <div className="text-center p-12">
                <p className="text-3xl lg:text-2xl xl:text-3xl pb-4">Hobby</p>
                <div className="flex justify justify-center items-center">
                  <span className="font-extrabold text-5xl lg:text-4xl xl:text-6xl align-text-middle px-3">
                    $ 79
                  </span>
                  <span className="font-normal text-xl text-gray-500 inline-block align-text-middle">
                    /month
                  </span>
                </div>
              </div>
              <div className="bg-gray-100 rounded-b-xl border-t-2 border-gray-200/20 p-10">
                <ul className="space-y-4">
                  <li className="flex">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 mr-3 text-green-500"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    <span className="text-gray-500">
                      when an unknown printer took a galley.
                    </span>
                  </li>
                  <li className="flex">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 mr-3 text-green-500"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    <span className="text-gray-500">
                      leap into electronic typesetting remaining.{" "}
                    </span>
                  </li>
                  <li className="flex">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 mr-3 text-green-500"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    <span className="text-gray-500">
                      ontaining Lorem Ipsum passages and more.
                    </span>
                  </li>
                </ul>
                <button
                  type="button"
                  className="w-full text-center bg-white text-lg text-indigo-600 mt-8 p-3 rounded shadow-xl transition hover:text-white hover:bg-indigo-600"
                >
                  Start your trial
                </button>
              </div>
            </div>
            <div className="lg:max-w-max mb-6 relative w-full bg-white rounded-xl shadow-xl border-2 border-indigo-600 lg:scale-110 z-10">
              <div className="text-center p-12">
                <p className="text-3xl lg:text-2xl xl:text-3xl pb-4 font-semibold">
                  Growth
                </p>
                <div className="flex justify justify-center items-center">
                  <span className="font-extrabold text-5xl lg:text-4xl xl:text-6xl align-text-middle px-3">
                    $ 149
                  </span>
                  <span className="font-normal text-xl text-gray-500 inline-block align-text-middle">
                    /month
                  </span>
                </div>
              </div>
              <div className="bg-gray-100 rounded-b-xl border-t-2 border-gray-200/20 p-10">
                <ul className="space-y-4">
                  <li className="flex">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 mr-3 text-green-500"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    <span className="text-gray-500">
                      when an unknown printer took a galley.
                    </span>
                  </li>
                  <li className="flex">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 mr-3 text-green-500"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    <span className="text-gray-500">
                      leap into electronic typesetting remaining.{" "}
                    </span>
                  </li>
                  <li className="flex">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 mr-3 text-green-500"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    <span className="text-gray-500">
                      ontaining Lorem Ipsum passages and more.
                    </span>
                  </li>
                  <li className="flex">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 mr-3 text-green-500"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    <span className="text-gray-500">
                      leap into electronic typesetting remaining.{" "}
                    </span>
                  </li>
                  <li className="flex">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 mr-3 text-green-500"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    <span className="text-gray-500">
                      ontaining Lorem Ipsum passages and more.
                    </span>
                  </li>
                </ul>
                <button
                  type="button"
                  className="w-full text-center bg-indigo-600 text-lg text-white mt-8 p-3 rounded shadow-xl transition hover:text-white hover:bg-indigo-700"
                >
                  Start your trial
                </button>
              </div>
              <div className="absolute rounded-full w-40 bg-indigo-600 text-white text-center text-sm tracking-wider px-4 py-1 -top-3 inset-x-0 mx-auto">
                MOST POPULAR
              </div>
            </div>
            <div className="flex-1 w-full mb-6 bg-white rounded-xl shadow-xl lg:scale-95">
              <div className="text-center p-12">
                <p className="text-3xl lg:text-2xl xl:text-3xl pb-4">Hobby</p>
                <div className="flex justify justify-center items-center">
                  <span className="font-extrabold text-5xl lg:text-4xl xl:text-6xl align-text-middle px-3">
                    $ 349
                  </span>
                  <span className="font-normal text-xl text-gray-500 inline-block align-text-middle">
                    /month
                  </span>
                </div>
              </div>
              <div className="bg-gray-100 rounded-b-xl border-t-2 border-gray-200/20 p-10">
                <ul className="space-y-4">
                  <li className="flex">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 mr-3 text-green-500"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    <span className="text-gray-500">
                      when an unknown printer took a galley.
                    </span>
                  </li>
                  <li className="flex">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 mr-3 text-green-500"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    <span className="text-gray-500">
                      leap into electronic typesetting remaining.{" "}
                    </span>
                  </li>
                  <li className="flex">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 mr-3 text-green-500"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    <span className="text-gray-500">
                      ontaining Lorem Ipsum passages and more.
                    </span>
                  </li>
                </ul>
                <button
                  type="button"
                  className="w-full text-center bg-white text-lg text-indigo-600 mt-8 p-3 rounded shadow-xl transition hover:text-white hover:bg-indigo-600"
                >
                  Start your trial
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Price;
