import ListMindmap from "./ListMindmap";
// import Confirm from "../items/confirm";
import { getSession } from "@auth0/nextjs-auth0";
import { redirect } from "next/navigation";

export const metadata = {
  title: "My Mindmap",
  description: "Generated by create next app",
};

const page = async () => {
  const { user } = await getSession();
  if (!user) {
    redirect("/api/auth/login");
  }
  return <ListMindmap sub={user?.sub} />;
};

export default page;
