import ListMindmap from "./[id]/ListMindmap";
// import Confirm from "../items/confirm";


export const metadata = {
  title: "My Mindmap",
  description: "Generated by create next app",
};

const page = () => {
  return <ListMindmap />;
};

export default page;
