CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "status" boolean DEFAULT false,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now());
);

CREATE TABLE "order_detail" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "products_id" integer NOT NULL,
  "orders_id" integer NOT NULL,
  "products_name" varchar(50) NOT NULL,
  "user_name" varchar(50) NOT NULL,
  "price" integer NOT NULL,
  "amount" integer NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now());
);


CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "email" varchar(100) NOT NULL,
  "phone" varchar(15) NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "price" integer DEFAULT 0,
  "quantity" integer NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "order_detail" ("user_id");

ALTER TABLE "products" ADD FOREIGN KEY ("id") REFERENCES "order_detail" ("products_id");

ALTER TABLE "order_detail" ADD FOREIGN KEY ("orders_id") REFERENCES "orders" ("id");


INSERT INTO user (name, phone, email)
VALUES
  ('Hoang An', '123456789', 'hoangan.web@gmail.com'),
  ('Dai The', '123456788', 'daithe@gmail.com.com'),
  ('Nguyen Duong', '123456787', 'nguyenduong@gmail.com'),
  ('Anh Quan', '123456786', 'anhquan@gmail.com'),
  ('Duy Tung', '666666666', 'duytung@gmail.com'),

INSERT INTO products (name, price, quantity) VALUES
  ('thuoc la', 30, 99),
  ('cafe',15 , 99),
  ('bong', 90, 99),
  ('game', 2, 99);

  INSERT INTO orders (status) VALUES
  (true),
  (false),
  (true),
  (false);



INSERT INTO order_detail (user_id, products_id, orders_id, products_name, user_name, price, amount) VALUES
  (6, 1, 1, 'thuoc la', 'Hoang An', 30, 8);
INSERT INTO order_detail (user_id, products_id, orders_id, products_name, user_name, price, amount) VALUES
  (16, 2, 2, 'cafe', 'Nguyen Duong', 15, 6);

  INSERT INTO order_detail (user_id, products_id, orders_id, products_name, user_name, price, amount) VALUES
  (2, 6, 6, 'bong', 'Dai The', 90, 2);
INSERT INTO order_detail (user_id, products_id, orders_id, products_name, user_name, price, amount) VALUES
  (1, 5, 5, 'game', 'Duy Tung', 2, 4);


select user.name,user.email,user.phone, orders.*,order_detail.price,order_detail.amount
from user
join 